# Generated by Django 3.2.9 on 2022-02-21 13:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('production_year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('rating', models.FloatField()),
                ('total_votes', models.IntegerField()),
                ('director', models.TextField(max_length=200)),
                ('writer', models.TextField(max_length=200)),
                ('actors', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=600)),
                ('genres', models.ManyToManyField(to='films.Genre')),
                ('languages', models.ManyToManyField(to='films.Language')),
            ],
        ),
    ]
